-- Step 1: delete bot registrations from completed/cancelled tournaments
WITH active_bot_ids AS (
  SELECT DISTINCT tr.user_id
  FROM tournament_registrations tr
  JOIN tournaments t ON t.id = tr.tournament_id
  JOIN profiles p ON p.user_id = tr.user_id
  WHERE p.display_name LIKE '[BOT]%'
    AND t.status NOT IN ('completed', 'cancelled')
),
bots_to_delete AS (
  SELECT user_id FROM profiles
  WHERE display_name LIKE '[BOT]%'
    AND user_id NOT IN (SELECT user_id FROM active_bot_ids)
)
DELETE FROM tournament_registrations
WHERE user_id IN (SELECT user_id FROM bots_to_delete);

-- Step 2: delete the orphaned bot profiles
DELETE FROM profiles
WHERE display_name LIKE '[BOT]%'
  AND user_id NOT IN (
    SELECT DISTINCT tr.user_id
    FROM tournament_registrations tr
    JOIN tournaments t ON t.id = tr.tournament_id
    WHERE t.status NOT IN ('completed', 'cancelled')
  );

-- Step 3: rename surviving active bots with first 9 Beyblade names
WITH ranked_active AS (
  SELECT user_id, ROW_NUMBER() OVER (ORDER BY user_id) AS rn
  FROM profiles WHERE display_name LIKE '[BOT]%'
),
new_names(rn, new_name) AS (
  VALUES (1, '[BOT] Tyson Granger'),
(2, '[BOT] Kai Hiwatari'),
(3, '[BOT] Ray Kon'),
(4, '[BOT] Max Tate'),
(5, '[BOT] Daichi Sumeragi'),
(6, '[BOT] Kenny'),
(7, '[BOT] Hilary Tachibana'),
(8, '[BOT] Hiro Granger'),
(9, '[BOT] Brooklyn Masefield')
)
UPDATE profiles p
SET display_name = nn.new_name
FROM ranked_active ra
JOIN new_names nn ON nn.rn = ra.rn
WHERE p.user_id = ra.user_id;

-- Step 4: insert remaining 247 new bots
INSERT INTO profiles (user_id, display_name) VALUES
(gen_random_uuid(), '[BOT] Garland Siebald'),
(gen_random_uuid(), '[BOT] Crusher'),
(gen_random_uuid(), '[BOT] Mystel'),
(gen_random_uuid(), '[BOT] Tala Valkov'),
(gen_random_uuid(), '[BOT] Bryan Kuznetsov'),
(gen_random_uuid(), '[BOT] Spencer'),
(gen_random_uuid(), '[BOT] Ian Papov'),
(gen_random_uuid(), '[BOT] Lee Wong'),
(gen_random_uuid(), '[BOT] Kevin Cheng'),
(gen_random_uuid(), '[BOT] Gary Tan'),
(gen_random_uuid(), '[BOT] Mariah Wong'),
(gen_random_uuid(), '[BOT] Michael Parker'),
(gen_random_uuid(), '[BOT] Eddy Wheeler'),
(gen_random_uuid(), '[BOT] Steve Patrick'),
(gen_random_uuid(), '[BOT] Emily York'),
(gen_random_uuid(), '[BOT] Rick Anderson'),
(gen_random_uuid(), '[BOT] Ozuma'),
(gen_random_uuid(), '[BOT] Dunga'),
(gen_random_uuid(), '[BOT] Mariam'),
(gen_random_uuid(), '[BOT] Joseph'),
(gen_random_uuid(), '[BOT] Robert Jürgens'),
(gen_random_uuid(), '[BOT] Johnny McGregor'),
(gen_random_uuid(), '[BOT] Enrique Giancarlo'),
(gen_random_uuid(), '[BOT] Oliver Polanski'),
(gen_random_uuid(), '[BOT] Zeo Zagart'),
(gen_random_uuid(), '[BOT] Gordo'),
(gen_random_uuid(), '[BOT] King'),
(gen_random_uuid(), '[BOT] Queen'),
(gen_random_uuid(), '[BOT] Gingka Hagane'),
(gen_random_uuid(), '[BOT] Kyoya Tategami'),
(gen_random_uuid(), '[BOT] Ryuga'),
(gen_random_uuid(), '[BOT] Kenta Yumiya'),
(gen_random_uuid(), '[BOT] Madoka Amano'),
(gen_random_uuid(), '[BOT] Benkei Hanawa'),
(gen_random_uuid(), '[BOT] Tsubasa Otori'),
(gen_random_uuid(), '[BOT] Yu Tendo'),
(gen_random_uuid(), '[BOT] Hyoma'),
(gen_random_uuid(), '[BOT] Gao'),
(gen_random_uuid(), '[BOT] Mei-Mei'),
(gen_random_uuid(), '[BOT] Chao Xin'),
(gen_random_uuid(), '[BOT] Masamune Kadoya'),
(gen_random_uuid(), '[BOT] Nile'),
(gen_random_uuid(), '[BOT] Damian Hart'),
(gen_random_uuid(), '[BOT] Jack'),
(gen_random_uuid(), '[BOT] Julian Konzern'),
(gen_random_uuid(), '[BOT] Sophie'),
(gen_random_uuid(), '[BOT] Wales'),
(gen_random_uuid(), '[BOT] Klaus'),
(gen_random_uuid(), '[BOT] Dragoord'),
(gen_random_uuid(), '[BOT] Yuki Mizusawa'),
(gen_random_uuid(), '[BOT] Aguma'),
(gen_random_uuid(), '[BOT] Bao'),
(gen_random_uuid(), '[BOT] Chris'),
(gen_random_uuid(), '[BOT] Johannes'),
(gen_random_uuid(), '[BOT] Herschel'),
(gen_random_uuid(), '[BOT] Nemesis'),
(gen_random_uuid(), '[BOT] Pluto'),
(gen_random_uuid(), '[BOT] Rago'),
(gen_random_uuid(), '[BOT] Zyro Kurogane'),
(gen_random_uuid(), '[BOT] Shinobu Hiryuin'),
(gen_random_uuid(), '[BOT] Maru'),
(gen_random_uuid(), '[BOT] Kite Unabara'),
(gen_random_uuid(), '[BOT] Eight Unabara'),
(gen_random_uuid(), '[BOT] Ren Kurenai'),
(gen_random_uuid(), '[BOT] Sakyo Kurayami'),
(gen_random_uuid(), '[BOT] Takanosuke Shishiya'),
(gen_random_uuid(), '[BOT] Genjuro'),
(gen_random_uuid(), '[BOT] Spike Bourne'),
(gen_random_uuid(), '[BOT] Captain Arrow'),
(gen_random_uuid(), '[BOT] Baihu Xiao'),
(gen_random_uuid(), '[BOT] Doji'),
(gen_random_uuid(), '[BOT] Merci'),
(gen_random_uuid(), '[BOT] Valt Aoi'),
(gen_random_uuid(), '[BOT] Shu Kurenai'),
(gen_random_uuid(), '[BOT] Rantaro Kiyama'),
(gen_random_uuid(), '[BOT] Wakiya Murasaki'),
(gen_random_uuid(), '[BOT] Daigo Kurogami'),
(gen_random_uuid(), '[BOT] Ken Midori'),
(gen_random_uuid(), '[BOT] Honcho'),
(gen_random_uuid(), '[BOT] Xander Shakadera'),
(gen_random_uuid(), '[BOT] Zac Kaneguro'),
(gen_random_uuid(), '[BOT] Lui Shirosagi'),
(gen_random_uuid(), '[BOT] Free De La Hoya'),
(gen_random_uuid(), '[BOT] Silas Karlisle'),
(gen_random_uuid(), '[BOT] Cuza Ackermann'),
(gen_random_uuid(), '[BOT] Joshua Burns'),
(gen_random_uuid(), '[BOT] Kristina Kuroda'),
(gen_random_uuid(), '[BOT] Theodore Glass'),
(gen_random_uuid(), '[BOT] Aiger Akabane'),
(gen_random_uuid(), '[BOT] Fubuki Sumiye'),
(gen_random_uuid(), '[BOT] Suoh Genji'),
(gen_random_uuid(), '[BOT] Ranjiro Kiyama'),
(gen_random_uuid(), '[BOT] Phi'),
(gen_random_uuid(), '[BOT] Hae-jin Oh'),
(gen_random_uuid(), '[BOT] Kyle Hakim'),
(gen_random_uuid(), '[BOT] Labancus'),
(gen_random_uuid(), '[BOT] Xavier Bogard'),
(gen_random_uuid(), '[BOT] Count Nightfell'),
(gen_random_uuid(), '[BOT] Evel Oxford'),
(gen_random_uuid(), '[BOT] Dante Koryu'),
(gen_random_uuid(), '[BOT] Arman Kusaba'),
(gen_random_uuid(), '[BOT] Delta Zakuro'),
(gen_random_uuid(), '[BOT] Gwyn Reynolds'),
(gen_random_uuid(), '[BOT] Pheng Hope'),
(gen_random_uuid(), '[BOT] Joe Lazure'),
(gen_random_uuid(), '[BOT] Lodin Haijima'),
(gen_random_uuid(), '[BOT] Arthur Peregrine'),
(gen_random_uuid(), '[BOT] Hikaru Hizashi'),
(gen_random_uuid(), '[BOT] Hyuga Hizashi'),
(gen_random_uuid(), '[BOT] Lain Valhalla'),
(gen_random_uuid(), '[BOT] Shasa Guten'),
(gen_random_uuid(), '[BOT] Bel Daizora'),
(gen_random_uuid(), '[BOT] Ranzo Kiyama'),
(gen_random_uuid(), '[BOT] Rashad Goodman'),
(gen_random_uuid(), '[BOT] Ilya Mao'),
(gen_random_uuid(), '[BOT] Pax Forsythe'),
(gen_random_uuid(), '[BOT] Quadra'),
(gen_random_uuid(), '[BOT] Bird Kazami'),
(gen_random_uuid(), '[BOT] Ekusu Kurosu'),
(gen_random_uuid(), '[BOT] Multi Nanairo'),
(gen_random_uuid(), '[BOT] Toko Aoi'),
(gen_random_uuid(), '[BOT] Nika Aoi'),
(gen_random_uuid(), '[BOT] Yugo Nansui'),
(gen_random_uuid(), '[BOT] Ukyo Ibuki'),
(gen_random_uuid(), '[BOT] Quon Limon'),
(gen_random_uuid(), '[BOT] Gabe Brunai'),
(gen_random_uuid(), '[BOT] Naoki Minamo'),
(gen_random_uuid(), '[BOT] Jin Aizawa'),
(gen_random_uuid(), '[BOT] Akira Yamatoga'),
(gen_random_uuid(), '[BOT] Clio Delon'),
(gen_random_uuid(), '[BOT] Kurt Baratier'),
(gen_random_uuid(), '[BOT] Norman Tarver'),
(gen_random_uuid(), '[BOT] Boa Alcazaba'),
(gen_random_uuid(), '[BOT] Ghasem Madal'),
(gen_random_uuid(), '[BOT] Countess'),
(gen_random_uuid(), '[BOT] Ashram'),
(gen_random_uuid(), '[BOT] Hartley'),
(gen_random_uuid(), '[BOT] Hoji Konda'),
(gen_random_uuid(), '[BOT] Sisco Karlisle'),
(gen_random_uuid(), '[BOT] Stan Hamburg'),
(gen_random_uuid(), '[BOT] Trad Vasquez'),
(gen_random_uuid(), '[BOT] Honey Guten'),
(gen_random_uuid(), '[BOT] Reina Ayabe'),
(gen_random_uuid(), '[BOT] Toko Kirishima'),
(gen_random_uuid(), '[BOT] Hyde'),
(gen_random_uuid(), '[BOT] Koji Konda'),
(gen_random_uuid(), '[BOT] Sasha Ayabe'),
(gen_random_uuid(), '[BOT] Ange Lopez'),
(gen_random_uuid(), '[BOT] Valtteri Bottas'),
(gen_random_uuid(), '[BOT] Shuichi Aizawa'),
(gen_random_uuid(), '[BOT] Tango Koryusai'),
(gen_random_uuid(), '[BOT] Kimeru'),
(gen_random_uuid(), '[BOT] Toko Sumiye'),
(gen_random_uuid(), '[BOT] Naru Akabane'),
(gen_random_uuid(), '[BOT] Tobisuke'),
(gen_random_uuid(), '[BOT] Gumita'),
(gen_random_uuid(), '[BOT] Ichika Kindo'),
(gen_random_uuid(), '[BOT] Fumiya Kindo'),
(gen_random_uuid(), '[BOT] Blonec'),
(gen_random_uuid(), '[BOT] Phelix Payne'),
(gen_random_uuid(), '[BOT] Yukio Kageyama'),
(gen_random_uuid(), '[BOT] Bashara Suiro'),
(gen_random_uuid(), '[BOT] Kana Akabane'),
(gen_random_uuid(), '[BOT] Taiga Akabane'),
(gen_random_uuid(), '[BOT] Kento Aoi'),
(gen_random_uuid(), '[BOT] Chiharu Aoi'),
(gen_random_uuid(), '[BOT] Ryota Kurogami'),
(gen_random_uuid(), '[BOT] Souta Kurogami'),
(gen_random_uuid(), '[BOT] Alexander Gilten'),
(gen_random_uuid(), '[BOT] Carl'),
(gen_random_uuid(), '[BOT] Igor'),
(gen_random_uuid(), '[BOT] Ataru Suranagi'),
(gen_random_uuid(), '[BOT] Jango Matoba'),
(gen_random_uuid(), '[BOT] Harry'),
(gen_random_uuid(), '[BOT] Laura'),
(gen_random_uuid(), '[BOT] Mick'),
(gen_random_uuid(), '[BOT] Judy'),
(gen_random_uuid(), '[BOT] David'),
(gen_random_uuid(), '[BOT] Andrew'),
(gen_random_uuid(), '[BOT] Ivan'),
(gen_random_uuid(), '[BOT] Raul'),
(gen_random_uuid(), '[BOT] Celine'),
(gen_random_uuid(), '[BOT] Mathilda'),
(gen_random_uuid(), '[BOT] Miguel'),
(gen_random_uuid(), '[BOT] Barthez'),
(gen_random_uuid(), '[BOT] Aaron'),
(gen_random_uuid(), '[BOT] Matis'),
(gen_random_uuid(), '[BOT] Claude'),
(gen_random_uuid(), '[BOT] Jeanne'),
(gen_random_uuid(), '[BOT] Rocamadour'),
(gen_random_uuid(), '[BOT] Rodrick'),
(gen_random_uuid(), '[BOT] Gordon'),
(gen_random_uuid(), '[BOT] Ygdrion'),
(gen_random_uuid(), '[BOT] Azure Eye'),
(gen_random_uuid(), '[BOT] Black Eye'),
(gen_random_uuid(), '[BOT] Gray Eye'),
(gen_random_uuid(), '[BOT] Violet Eye'),
(gen_random_uuid(), '[BOT] Hartz'),
(gen_random_uuid(), '[BOT] Dyna'),
(gen_random_uuid(), '[BOT] Jinya Konda'),
(gen_random_uuid(), '[BOT] Ryusho'),
(gen_random_uuid(), '[BOT] Ryuto'),
(gen_random_uuid(), '[BOT] Ryuga Hizashi'),
(gen_random_uuid(), '[BOT] Teru Saotome'),
(gen_random_uuid(), '[BOT] Tetsuya Watarigani'),
(gen_random_uuid(), '[BOT] Tobio Oike'),
(gen_random_uuid(), '[BOT] Dan Sodo'),
(gen_random_uuid(), '[BOT] Reiji Mizuchi'),
(gen_random_uuid(), '[BOT] Hikaru Hasama'),
(gen_random_uuid(), '[BOT] Yuu'),
(gen_random_uuid(), '[BOT] Ginga Hagane Sr'),
(gen_random_uuid(), '[BOT] Ryo Hagane'),
(gen_random_uuid(), '[BOT] Hokuto'),
(gen_random_uuid(), '[BOT] Daidoji'),
(gen_random_uuid(), '[BOT] Argo Garcia'),
(gen_random_uuid(), '[BOT] Selen Garcia'),
(gen_random_uuid(), '[BOT] Ian Garcia'),
(gen_random_uuid(), '[BOT] Enzo Garcia'),
(gen_random_uuid(), '[BOT] Zidane Garcia'),
(gen_random_uuid(), '[BOT] Sora Akatsuki'),
(gen_random_uuid(), '[BOT] Wang Hu Zhong'),
(gen_random_uuid(), '[BOT] Faust'),
(gen_random_uuid(), '[BOT] Ryutaro Fukami'),
(gen_random_uuid(), '[BOT] Tsubasa Otori Sr'),
(gen_random_uuid(), '[BOT] Hibiki'),
(gen_random_uuid(), '[BOT] Kuon'),
(gen_random_uuid(), '[BOT] Drago'),
(gen_random_uuid(), '[BOT] Reiki'),
(gen_random_uuid(), '[BOT] Sho Tenma'),
(gen_random_uuid(), '[BOT] Tooru Genjuro'),
(gen_random_uuid(), '[BOT] Cheshire'),
(gen_random_uuid(), '[BOT] Diablo'),
(gen_random_uuid(), '[BOT] Sumeragi'),
(gen_random_uuid(), '[BOT] Mizuho'),
(gen_random_uuid(), '[BOT] Kira Hayama'),
(gen_random_uuid(), '[BOT] Yoshio Iwayama'),
(gen_random_uuid(), '[BOT] Karura'),
(gen_random_uuid(), '[BOT] Salhan'),
(gen_random_uuid(), '[BOT] Goki'),
(gen_random_uuid(), '[BOT] Tithi'),
(gen_random_uuid(), '[BOT] Dynamis'),
(gen_random_uuid(), '[BOT] Aleksei'),
(gen_random_uuid(), '[BOT] Nowaguma'),
(gen_random_uuid(), '[BOT] Kakeru'),
(gen_random_uuid(), '[BOT] Shinya'),
(gen_random_uuid(), '[BOT] Souga'),
(gen_random_uuid(), '[BOT] Naoki'),
(gen_random_uuid(), '[BOT] Yuuya'),
(gen_random_uuid(), '[BOT] Kazu'),
(gen_random_uuid(), '[BOT] Kouki'),
(gen_random_uuid(), '[BOT] Kouhei'),
(gen_random_uuid(), '[BOT] Shougo');

-- Final verification
SELECT COUNT(*) FILTER (WHERE display_name LIKE '[BOT]%') AS total_bots,
       COUNT(*) FILTER (WHERE display_name LIKE '[Guest]%') AS guests
FROM profiles;