// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhqxwcnnyqrlizlowtgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpocXh3Y25ueXFybGl6bG93dGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4MjE4ODAsImV4cCI6MjA5MTM5Nzg4MH0.r6YQZgfRIRSOGBiZCb7HvLR8cnpX3QXRlxR-owBdLO4";

const memoryStorage = new Map<string, string>();
let resolvedStorage: Storage | null | undefined;

const getSafeBrowserStorage = () => {
  if (resolvedStorage !== undefined) return resolvedStorage;
  if (typeof window === "undefined") {
    resolvedStorage = null;
    return resolvedStorage;
  }

  for (const storage of [window.localStorage, window.sessionStorage]) {
    try {
      const testKey = "supabase-storage-test";
      storage.setItem(testKey, "1");
      storage.removeItem(testKey);
      resolvedStorage = storage;
      return resolvedStorage;
    } catch {
      continue;
    }
  }

  resolvedStorage = null;
  return resolvedStorage;
};

const authStorage = {
  getItem: (key: string) => {
    const storage = getSafeBrowserStorage();
    if (storage) return storage.getItem(key);
    return memoryStorage.get(key) ?? null;
  },
  setItem: (key: string, value: string) => {
    const storage = getSafeBrowserStorage();
    if (storage) {
      storage.setItem(key, value);
      return;
    }
    memoryStorage.set(key, value);
  },
  removeItem: (key: string) => {
    const storage = getSafeBrowserStorage();
    if (storage) {
      storage.removeItem(key);
      return;
    }
    memoryStorage.delete(key);
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});